name: Pre-build assets

on:
  push:
    branches: [develop, version-15, version-16]

jobs:
  assets:
    name: Pre-build assets
    uses: frappe/pilot/.github/workflows/app-assets.yml@develop
    permissions:
      contents: write
